#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Try to locate Composer autoloader.
 */
$autoloadPaths = [
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
    __DIR__.'/../../autoload.php',
    __DIR__.'/../autoload.php',
];

$autoloadFound = false;
foreach ($autoloadPaths as $autoloadPath) {
    if (file_exists($autoloadPath)) {
        require_once $autoloadPath;
        $autoloadFound = true;
        break;
    }
}

if (!$autoloadFound) {
    fwrite(STDERR, "Autoload file not found. Run `composer install`.\n");
    exit(1);
}

use Obresoft\Racoony\Application;

(new Application())->run();
